#!/usr/bin/env python3
"""Generate a human-readable task overview for DeFi Bench v1."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROTOCOL_LABELS = {
    "uniswap_v3": "Uniswap V3",
    "aave_v3": "Aave V3",
    "maker_sky": "Maker / Sky",
    "lido": "Lido",
    "pendle": "Pendle",
    "gmx": "GMX",
}


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def compact_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def constraint_summary(constraints: list[dict]) -> str:
    if not constraints:
        return "-"
    return "; ".join(compact_json(item) for item in constraints)


def scenario_summary(scenario: dict) -> str:
    positions = scenario["wallet_state"].get("positions", [])
    if not positions:
        return "none"
    counts = Counter(item.get("type", "unknown") for item in positions)
    return ", ".join(f"{kind} x{count}" for kind, count in sorted(counts.items()))


def optimization_summary(gold: dict) -> str:
    config = gold.get("economic_regret_config")
    if not config:
        return "no"
    return (
        f"yes; best={config['best_candidate_id']}; "
        f"utility={config['best_valid_utility']}; "
        f"formula={config['utility_formula']}"
    )


def protocol_section(protocol: str) -> str:
    env_dir = ROOT / "envs" / protocol
    tasks = load_jsonl(env_dir / "tasks.jsonl")
    gold_by_id = {row["task_id"]: row for row in load_jsonl(env_dir / "gold.jsonl")}
    scenarios_by_id = {row["task_id"]: row for row in load_jsonl(env_dir / "scenarios.jsonl")}

    rows = [
        f"## {PROTOCOL_LABELS[protocol]}",
        "",
        "| Task | Diff | Type | Request | Scenario positions | Economic regret | Hard constraints |",
        "|---|---|---|---|---|---|---|",
    ]
    for task in tasks:
        task_id = task["task_id"]
        gold = gold_by_id[task_id]
        scenario = scenarios_by_id[task_id]
        rows.append(
            "| "
            + " | ".join(
                [
                    f"`{task_id}`",
                    task["difficulty"],
                    task["task_type"],
                    task["user_request"],
                    scenario_summary(scenario),
                    optimization_summary(gold),
                    constraint_summary(gold["hard_constraints"]),
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def main() -> None:
    manifest = load_json(ROOT / "manifest.json")
    protocols = manifest["protocols"]
    all_tasks = []
    all_gold = []
    all_scenarios = []
    for protocol in protocols:
        env_dir = ROOT / "envs" / protocol
        all_tasks.extend(load_jsonl(env_dir / "tasks.jsonl"))
        all_gold.extend(load_jsonl(env_dir / "gold.jsonl"))
        all_scenarios.extend(load_jsonl(env_dir / "scenarios.jsonl"))

    difficulty_counts = Counter(row["difficulty"] for row in all_tasks)
    type_counts = Counter(row["task_type"] for row in all_tasks)
    optimization_count = sum(1 for row in all_gold if row["economic_regret_applicable"])
    scenario_with_positions = sum(1 for row in all_scenarios if row["wallet_state"].get("positions"))

    parts = [
        "# DeFi Bench v1 Task Overview",
        "",
        "This file is generated by `scripts/generate_task_overview.py` for human review.",
        "",
        "## Summary",
        "",
        f"- Dataset: `{manifest['dataset']}`",
        f"- Version: `{manifest['version']}`",
        f"- Total tasks: {len(all_tasks)}",
        f"- Total scenarios: {len(all_scenarios)}",
        f"- Difficulty counts: {dict(sorted(difficulty_counts.items()))}",
        f"- Task type counts: {dict(sorted(type_counts.items()))}",
        f"- Optimization tasks with economic regret: {optimization_count}",
        f"- Scenarios with initial positions: {scenario_with_positions}",
        "",
    ]
    parts.extend(protocol_section(protocol) for protocol in protocols)
    (ROOT / "task_overview.md").write_text("\n".join(parts) + "\n", encoding="utf-8")
    print("OK: wrote task_overview.md")


if __name__ == "__main__":
    main()
